### ISSUE TITLE
Error when building on S390x

### ISSUE THREAD

**Issue by james-crowley** [creack/goselect#14]
I am trying to build a binary for [Packer](https://github.com/hashicorp/packer) and it seems to pull in your library.

When the build gets to your library it reports this error:

```
==> Building...
Number of parallel builds: 3

-->     linux/s390x: github.com/hashicorp/packer

1 errors occurred:
--> linux/s390x error: exit status 2
Stderr: # github.com/hashicorp/packer/vendor/github.com/creack/goselect
vendor/github.com/creack/goselect/fdset.go:14:14: undefined: NFDBITS
vendor/github.com/creack/goselect/fdset.go:19:14: undefined: NFDBITS
vendor/github.com/creack/goselect/fdset.go:24:21: undefined: NFDBITS

``` 

This error looks identical to other issues raised on this repo like, #9 and #5 . I am not any Go expert, so it is hard for me to give you guys suggestions on possible fixes. 

It looks like that last commit might have something to do with it though, #13 . This commit looked like it added support for s390x, so I am not sure what is going on. 

Any help you can provide is appreciated. Additionally, if you need a s390x platform to test on, let me know. IBM does offer access to a mainframe for developers, you can check it out [here](https://developer.ibm.com/linuxone/).

**Comment by creack** [comment]
I'll take a look over the weekend.

**Comment by james-crowley** [comment]
Thanks! If you need anything please let me know. Also my Go version is `go version go1.11.5 linux/s390x`.

**Comment by creack** [comment]
goselect did indeed support s390x already, but packer used an older version. I created a PR to packer to use the latest goselect. There were also an issue in golang.org/x/crypto preventing compilation on s390x so I bumped it as well.

See hashicorp/packer#7567

**Comment by james-crowley** [comment]
@creack Thanks so much! I am hoping the PR gets approved and merged soon. Looking forward to using Packer on s390x.

Feel free to close out this issue when you want, either now or when the PR gets accepted!

**Comment by james-crowley** [comment]
Closing due to https://github.com/hashicorp/packer/pull/7567

Thanks for the quick response!
