### ISSUE TITLE
Please cross-reference license somewhere

### ISSUE THREAD

**Issue by QuLogic** [creack/goselect#15]
Because [my reviewer really wants this to happen](https://bugzilla.redhat.com/show_bug.cgi?id=1763147#c2), please add a note of the license in the readme/sources.

**Comment by creack** [comment]
I'm not really sure to understand what you are asking. Would you have an example of an other MIT repository that would comply with the reviewer's request?

Adding MIT mentions on every file seems overkill. I can add something to the Readme, but not sure what.

**Comment by QuLogic** [comment]
Well, the reviewer said:

> Upstream needs to clarify this somehow, because it's not clear at the moment.
> The best way to do this is to add a comment in the actual source files.
> If there's any reason upstream has to object this, they could do something else, such as adding a statement in the README file.
> 
> There's might be a chance that "this software" in the MIT license text could be understood as referring to whatever is in the same directory or tarball, but I don't know whether that's universally understood and would prefer a clarification to guessing.

though I agree with you and think adding it to all files is excessive. I suggest just adding a short bit in the readme, like [minify](https://github.com/tdewolff/minify#license) or [parse](https://github.com/tdewolff/parse#license).

**Comment by creack** [comment]
Done on v0.1.1

**Comment by QuLogic** [comment]
Thanks!
