### ISSUE TITLE
missing arm64 support

### ISSUE THREAD

**Issue by jolan** [creack/goselect#5]
linux/arm64 boards are starting to ship in volume (i.e. ODROID-C2) and this platform is officially supported by golang.

I wasn't sure how to handle darwin/arm64 since I can't test that but this diff works for linux/arm64

```diff
--- a/vendor/github.com/creack/goselect/fdset_64.go
+++ b/vendor/github.com/creack/goselect/fdset_64.go
@@ -1,4 +1,4 @@
-// +build amd64,!darwin,!netbsd,!openbsd
+// +build amd64 arm64 !darwin !netbsd !openbsd
```

**Comment by creack** [comment]
Thanks for the patch.

**Comment by jolan** [comment]
Hi,

Unfortunately, what you committed doesn't work on my arm64 machine (nor does it work on my amd64 machine)

```bash
$ go get -u github.com/creack/goselect
# github.com/creack/goselect
go/src/github.com/creack/goselect/fdset.go:14: undefined: NFDBITS
go/src/github.com/creack/goselect/fdset.go:19: undefined: NFDBITS
go/src/github.com/creack/goselect/fdset.go:24: undefined: NFDBITS
```

I wasn't familiar with the build notations and was just trying to help someone from #archlinux-arm real quick.  Looking now, I believe it should be:

```
// +build amd64,arm64 !darwin,!netbsd,!openbsd
```

Which works ok on both my linux/amd64 and linux/arm64 machines.

**Comment by creack** [comment]
I need to reconfigure my raspberry pi to actually run the tests ^^ I just tested on darwin/amd64. Will push that fix

**Comment by creack** [comment]
@jolan Can you try again? This time, I made sure that the cross compile worked.

**Comment by jolan** [comment]
Can confirm it a native compile works too, thanks!
