### ISSUE TITLE
Support mips/mipsle/mips64/mips64le GOARCH

### ISSUE THREAD

**Issue by maddie** [creack/goselect#9]
Currently it seems this library doesn't support `mips/mipsle/mips64/mips64le`, when compiling the following error would appear:

```
# github.com/creack/goselect
../../../github.com/creack/goselect/fdset.go:14:14: undefined: NFDBITS
../../../github.com/creack/goselect/fdset.go:19:14: undefined: NFDBITS
../../../github.com/creack/goselect/fdset.go:24:21: undefined: NFDBITS
```

Manually adding `mips/mipsle` to `fdset_32.go` and `mips64/mips64le` to `fdset_64.go` build flag seems to compile successfully, however I'm not sure if this is the correct way to do it.

If it's OK to solve the problem like I mentioned above, I would be happy to send in a PR.

Thanks!

**Comment by creack** [comment]
I don't have a mips platform available so can't test it, but if your change works and the tests pass, then go for it and submit a PR, it is more than welcome :)

**Comment by maddie** [comment]
PR submitted, thanks!
